from __future__ import annotations

from enum import Enum


PROTOCOL_VERSION = 1
DEFAULT_BIND_IP = "0.0.0.0"
DEFAULT_PORT = 5000
DEFAULT_TTL = 10
DEFAULT_SOCKET_BUFFER_SIZE = 65_535
DEFAULT_SOCKET_TIMEOUT_SECONDS = 0.2
NODE_ID_PREFIX = "DEVICE"
DEFAULT_BROADCAST_ADDRESS = "255.255.255.255"
DEFAULT_DISCOVERY_INTERVAL_SECONDS = 2.0
DEFAULT_HEARTBEAT_INTERVAL_SECONDS = 2.0
DEFAULT_NEIGHBOR_TIMEOUT_SECONDS = 10.0
DEFAULT_STALE_CHECK_INTERVAL_SECONDS = 1.0
DEFAULT_RELIABLE_ACK_TIMEOUT_SECONDS = 1.0
DEFAULT_RELIABLE_MAX_RETRIES = 3
DEFAULT_RETRANSMISSION_CHECK_INTERVAL_SECONDS = 0.05
DEFAULT_GBN_WINDOW_SIZE = 4
DEFAULT_GBN_ACK_TIMEOUT_SECONDS = 1.0
DEFAULT_GBN_MAX_RETRANSMISSIONS = 20
DEFAULT_GBN_CHECK_INTERVAL_SECONDS = 0.05
DEFAULT_ADAPTIVE_EVAL_INTERVAL_SECONDS = 2.0


class PacketType(str, Enum):
    DISCOVERY = "DISCOVERY"
    DISCOVERY_RESPONSE = "DISCOVERY_RESPONSE"
    ROUTING_UPDATE = "ROUTING_UPDATE"
    MESSAGE = "MESSAGE"
    FILE_CHUNK = "FILE_CHUNK"
    ACK = "ACK"
    STATUS = "STATUS"
    HEARTBEAT = "HEARTBEAT"


class NodeStatus(str, Enum):
    ACTIVE = "ACTIVE"
    STOPPED = "STOPPED"
    DISCONNECTED = "DISCONNECTED"


PACKET_TYPE_VALUES = {packet_type.value for packet_type in PacketType}
